environment:
  matrix:
    - nodejs_version: "8"

init:
  - git config --global core.symlinks true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - choco install imagemagick --version 7.0.7.6
  - choco install ffmpeg --version 3.4.2
  - yarn

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

test_script:
  - yarn build
  - yarn flow-typed install
  # - yarn test

# Don't actually build.
build: off

artifacts:
  path: 'coverage'
  name: Coverage

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false